services:
  postgres:
    image: postgres:17
    container_name: todo-app-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: todo
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
